SELECT COUNT(*) 
FROM SALES 
WHERE DATE = '2023-03-18';

SELECT COUNT(*) 
FROM SALES AS S
LEFT JOIN CUSTOMERS AS C 
ON S.CUSTOMER_ID = C.CUSTOMER_ID
WHERE C.FIRST_NAME = 'John' AND C.LAST_NAME = 'Doe';

SELECT  COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_CUSTOMERS,
		SUM(REVENUE) / COUNT(DISTINCT CUSTOMER_ID) AS AVG_SPEND
FROM SALES
WHERE DATE BETWEEN '2023-01-01' AND '2023-01-31';

SELECT I.DEPARTMENT
FROM ITEMS AS I
LEFT JOIN SALES AS S
ON S.ITEM_ID = I.ITEM_ID
WHERE DATE BETWEEN '2022-01-01' AND '2022-12-31'
GROUP BY I.DEPARTMENT
HAVING SUM(REVENUE) > 600; 

SELECT MAX(REVENUE) AS MAX_REVENUE, MIN(REVENUE) AS MIN_REVENUE
FROM SALES;

SELECT *
FROM SALES
WHERE (SELECT MAX(REVENUE) FROM SALES);